config/routes.rb
Rails.application.routes.draw do

  resources :users
  get  'home/about' => 'home#about'
  resources :posts 
  get  '/result'    => 'posts#result'
  post '/result'    => 'posts#result'
  root :to          => 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :users, :dependent => :destroy

  validates :name,  :presence => true
  validates :title, :presence => true, :length => { :minimum => 1 }
  paginates_per 3

  enum category: { DailyLife: 0, Programming: 1, Study: 2, Book: 3, Food: 4, Other: 9 }     
                         
  #入力内容による絞り込み
  scope :search, ->(word) {
    where("content like ? or title like ?", "%#{sanitize_sql_like(word)}%","%#{sanitize_sql_like(word)}%")
  }

  #カテゴリー選択による絞り込み
  scope :get_by_category, ->(category) {
    where(category: category)
  }
  
  mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    before_action :get_new_posts
    def get_new_posts
        @new_posts = Post.all.order(created_at: :desc).limit(6)
    end
end

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
#   def create
#     @post = Post.find(params[:post_id])
#     @comment = @post.comments.create(params[:comment])
#     redirect_to post_path(@post)
#   end

#   def destroy
#     @post = Post.find(params[:post_id])
#     @comment = @post.comments.find(params[:id])
#     @comment.destroy
#     redirect_to post_path(@post)
#   end
# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per_page(3)
    # @posts = Post.page(params[:page]).order(created_at: :desc)
    @post = Post.find_by(id: params[:id])
    # 変更点
    if params[:search].present? 
      @posts = @posts.search params[:search]
    end
    # 変更点
    if params[:category].present?
      @posts = @posts.get_by_category params[:category]
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @user = User.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def result
    @post = Post.find_by_id(id: params[:id])
    if @post 
      @msg = nil
    else
      @msg = "検索結果がありません"
    end
  end

  def check
    @posts = Post.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :category, :picture)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    render :layout => nil
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @post = Post.all
    render :layout => nil
  end

  # GET /users/1/edit
  def edit
    @post = Post.all
    render :layout => nil
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:post_id, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  # ここではエラーメッセージがある場合はエラーメッセージを返す処理を行います。
  def error_message(message)
    if message
      message
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="col-md-8">
  <h1 style="color:#333; margin-top:200px; text-align:center;">ブログのデモアプリです。</h1>
</div>

app/views/layouts/_test.html.erb
<p>aaaaaa</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!----------------HEAD------------------>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>HiroBlog.</title>

    <!--[if lt IE 9]> 
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!--Slick of Slider-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="/slick.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/slick-theme.css"/>
    <link rel="stylesheet" type="text/css" href="/slick.css"/>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!---Bootstrap-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integritycs="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js" integrity="sha384-u/bQvRA/1bobcXlcEYpsEdFVK/vJs3+T+nXLsBYJthmdBuavHvAW6UsmqO2Gd/F9" crossorigin="anonymous"></script> 

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<!----------------HEAD------------------>
  <body class="bg-white">
  
<!-------------- NAVBAR ---------------->
    <nav class="navbar navbar-expand-md navbar-dark bg-info m-0" style="border-radius:30px;">
      <div class="navbar-brand">
        <%= link_to 'DEMO BOLG', '/posts', class: "nav-link", style: "color:black;font-weight:bold;" %>
      </div>

      <button class="navbar-toggler bg-dark float-right" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse justify-content-end"  id="navbarNav4">
        <ul class="navbar-nav">
          <li class="nav-item mx-3">
            <%= link_to 'HOME', '/posts', class: "nav-link" %>
          </li>
          <li class="nav-item mx-3">
            <%= link_to 'ABOUT', '/home/about', class: "nav-link" %>
          </li>
          <li class="nav-item mx-3">
            <%= link_to 'NEW POST', new_post_path, class: "nav-link" %>
          </li>
        </ul>

        <%= form_tag(posts_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
  　　　   <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2" %>
  　　　   <%= submit_tag 'Search', class: "btn btn-dark my-2 my-sm-0" %>
　　　　　<% end %>
      </div>
    </nav>
<!-------------- /NAVBAR --------------->
<!---------------- Slider -------------->
    <div class="container">
      <div class="row">
        <div class="offset-md-1 col-md-10 col-xs-12 mt-4">
          <%= render 'parts/slider' %>
        </div>
      </div>
<!------------- /Slider ---------------->
<!------------- Content ---------------->
      <div class="row">
  <!----------------MainContent---------------->
        <%= yield %>
  <!----------------/MainContent---------------->
  <!----------------Sidebar---------------->
        <div class="col-md-4 col-xs-12">
          <div class="card my-4">
            <h5 class="card-header">カテゴリー</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <%= link_to "日常",controller:"posts",action:"index",category: 0 %>
                    </li>
                    <li>
                      <%= link_to "プログラミング",controller:"posts",action:"index",category: 1 %>
                    </li>
                    <li>
                      <%= link_to "勉強",controller:"posts",action:"index",category: 2 %>
                    </li>
                    <li>
                      <%= link_to "本",controller:"posts",action:"index",category: 3 %>
                    </li>
                    <li>
                      <%= link_to "食べ物",controller:"posts",action:"index",category: 4 %>
                    </li>
                    <li>
                      <%= link_to "その他",controller:"posts",action:"index",category: 5 %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="card my-4">
            <h5 class="card-header">最新記事</h5>
            <div class="card-body">
              <ul class="list-unstyled text-dark">
                <%@new_posts.each do|post|%>
                  <li>
                    <%= link_to post.title,post %>
                  </li> 
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <!----------------/Sidebar---------------->
<!------------ /Content ---------------->
<!------------ Footer ------------------>
    <footer class="footer py-5">
      <div class="container">
        <p class="m-0 text-center text-dark">Copyright &copy; 2018</p>
      </div>
    </footer>
<!----------- /Footer ------------------>
<!---------- SliderJS ------------------>
    <script>
      $(function(){
        $('.slider').slick({
          infinite: true,
          dots:true,
          slidesToShow: 1,
          centerMode: true, //要素を中央寄せ
          centerPadding:'200px', //両サイドの見えている部分のサイズ
          autoplay:true, //自動再生
          responsive: [{
               breakpoint: 480,
                    settings: {
                         centerMode: false,
               }
          }]
        });
      });
    </script>
<!--------- /SliderJS ------------------>
  </body>
</html>

app/views/parts/_slider.html.erb
<div class="slider">
            <div><%= image_tag("waterIMGL2609_TP_V4.jpg", width:"100%", ) %></div>
            <div><%= image_tag("WPIMGL2488_TP_V4.jpg", width:"100%", ) %></div>
            <div><%= image_tag("WPIMGL2502_TP_V4.jpg", width:"100%", ) %></div>
            <div><%= image_tag("WPIMGL2745_TP_V4.jpg", width:"100%", ) %></div>
            <div><%= image_tag("WPIMGL2771_TP_V4.jpg", width:"100%", ) %></div>
            <div><%= image_tag("WPIMGL2773_TP_V4.jpg", width:"100%", ) %></div>
            <div><%= image_tag("WPIMGL2781_TP_V4.jpg", width:"100%", ) %></div>
            <div><%= image_tag("WPIMGL2784_TP_V4.jpg", width:"100%", ) %></div>
</div>

app/views/posts/_form.html.erb
<div class="col-md-7 bg-light " style="border-radius: 30px;">
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


　 
  <div class="field">
    <%= form.label :name, :html => {:class => 'name'}  %>
    <%= form.text_field :name, :style => 'width: 70%;'%>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, :style => 'width: 70%;' %>
  </div>

<!--   追加箇所　　　-->
  <div class="field">
    <p>category</p>
    <%= form.select :category, Post.categories.keys%>
  </div>

  <div class="field ">
    <%= form.label :content %>
    <%= form.text_area :content, :style => 'width: 70%; height:300px;' %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :post_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>
<%= link_to 'Back', posts_path %>
</div>

<div class="offset-md-1"></div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="col-md-8">

  <p id="notice"><%= notice %></p>

  <% @posts.each do |post| %>
    <div class="card mb-4">
      <h2 class="card-title card-header bg-dark text-light"><%= post.title %></h2>
      <div class="card-body">
        <p class="card-text">
          <%= post.content.truncate(30) %>
        </p>
        <%= link_to 'もっと見る', post, class:"btn btn-info text-light"%>
      </div>
      <div class="card-footer text-muted">
        <p>
          投稿者:<%= post.name %>  
          投稿日時:<%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
          カテゴリー:<%= link_to post.category ,controller:"posts",action:"index",category: post.category %>
          <%= link_to '編集', edit_post_path(post) %>
          <%= link_to '削除', post, method: :delete, data: { confirm: '本当に削除してよろしいですか?' } %>
        </p>
      </div>
    </div>
  <% end %>   
           
          <!--ページネーション-->
  <%= paginate @posts %>
          
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/search.html.erb
<div class="col-md-8">

  <p id="notice"><%= notice %></p>

  <% @posts.each do |post| %>
    <div class="card mb-4">
      <h2 class="card-title card-header bg-dark text-light"><%= post.title %></h2>
      <div class="card-body">
        <p class="card-text">
          <%= post.content.truncate(30) %>
        </p>
        <%= link_to 'もっと見る', post, class:"btn btn-info text-light"%>
      </div>
      <div class="card-footer text-muted">
        <p>
          投稿者:<%= post.name %>  
          投稿日時:<%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
          カテゴリー:<%= link_to post.category ,controller:"posts",action:"index",category: post.category %>
          <%= link_to '編集', edit_post_path(post) %>
          <%= link_to '削除', post, method: :delete, data: { confirm: '本当に削除してよろしいですか?' } %>
        </p>
      </div>
    </div>
  <% end %>   
           
          <!--ページネーション-->
  <%= paginate @posts %>
          
</div>

app/views/posts/show.html.erb
<div class="col-md-8">
　 
  <p id="notice"><%= notice %></p>

　 <div class="card">
    <h2 class="card-title card-header bg-dark text-light"><%= @post.title %></h2>
    <div class="card-body">
      <p>
        <strong>Picture:</strong>
        <%= image_tag(@post.picture_url, style: "width: 80%;") if @post.picture.present?  %>
      </p>
      <p class="card-text"><%=  simple_format @post.content %></p>
    </div>
    <div class="card-footer text-muted">
      <p>
        投稿者:<%= @post.name %>  
        投稿日時:<%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
        カテゴリー:<%= @post.category %>
        <%= link_to '編集', edit_post_path(@post) %>
        <%= link_to '削除', @post, method: :delete, data: { confirm: '本当に削除してよろしいですか?' } %>
        <%= link_to '戻る', posts_path %>
      </p>
    </div>
　 </div>
  <br><strong>コメント: <%= @post.users.count %>　件</strong></br>

  <% @user.each do |comment| %>
    <% if comment.post_id == @post.id %>
      <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S")%></br>
      <%= comment.comment %>
      <hr>
    <% end %>
  <% end %>

  
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :post_id %>
    <%= form.select :post_id, @post.collect { |post| [post.title, post.id] } %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.post_id %></td>
        <td><%= user.comment %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @user.post_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @user.comment %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>